import type { Metadata } from "next";
import "../../../globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/template-admin/app-sidebar";
import Header from "@/components/template-admin/header";
import { getUser } from "@/lib/auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

// Protected route
// 1. server components => tambahin async
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 2. ambil session dari getUser()
  const { session } = await getUser();

  // 3. buat kondisi, jika session tidak ada maka redirect ke halaman "/dashboard/sign-in"
  if (!session) {
    return redirect("/dashboard/sign-in");
  }
  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <Header />
        <main className="py-4 px-6">{children}</main>
      </SidebarInset>
    </SidebarProvider>
  );
}
