import type { Metadata } from "next";
import "../../../globals.css";
import { getUser } from "@/lib/auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Protected route
// 1. server components => tambahin async
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 2. ambil session dan user dari getUser()
  const { session, user } = await getUser();

  // 3. buat kondisi, jika session ada dan user.role adalah "superadmin" maka redirect ke halaman "/dashboard"
  if (session && user.role === "superadmin") {
    return redirect("/dashboard");
  }
  return <>{children}</>;
}
